name: Requirement Alphanumeric name
title: "Requirement title"
description: "Requirement description"
annotations: ["error::undecorated"]
release: 2023.1.2
priority: abc
suggested_by: economy1
complexity_points: 78
uncertainity_points: jp
assignees: Business
approved_by: shoyeb@rainfallone
